version: '3.7'

services:
    api:
        build: .
        container_name: enterprises-api
        volumes:
            - ./:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
        depends_on:
            - db
    db:
        image: mysql:8.0.28
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: enterprises-api
        ports:
            - 3306:3306